### ISSUE TITLE
Consistently getting `$actualApply is not a function` when running Cypress tests 

### ISSUE THREAD

**Issue by arcaderob** [ljharb/call-bind-apply-helpers#2] opened 2024-12-07 21:52 UTC
My project recently upgraded from React 18.2.0 to 18.3.1 and your package is now a part of my project as a dependency. If I use `npm ls call-bind-apply-helpers` I get

```
@{redacted monorepo root}
└─┬ @{redacted project root}
  └─┬ eslint-plugin-jsx-a11y@6.10.2
    └─┬ array-includes@3.1.8
      └─┬ call-bind@1.0.8
        └── call-bind-apply-helpers@1.0.0
```

When I try to run my Cypress tests, I am getting the error `$actualApply is not a function`, but I cannot figure out why this is the case.

**Comment by ljharb** [comment] 2024-12-07 22:15
hmm, which browser is this occurring in? can you provide the full stack trace?

**Comment by ljharb** [comment] 2024-12-07 22:18
Also, can you perhaps try to figure out what `$actualApply` is at that time, if not a function?

**Comment by arcaderob** [comment] 2024-12-07 22:20
It's actually not running in a browser. It is from the terminal running Cypress tests for Storybook.
I am not even sure why this is being called at all. I had never seen this package before yesterday and now it is causing my tests to fail with the error `$actualApply is not a function`.

I can do some more digging and try to determine why it is failing and what $actualApply is when the test fails.

**Comment by ljharb** [comment] 2024-12-07 22:22
I recently refactored `call-bind` to extract some pieces of it into this newly created package, which is why this package won't be something you've seen before :-)

I tested it pretty extensively but I may indeed have missed something.

**Comment by arcaderob** [comment] 2024-12-07 22:26
I modified index.js to be 
```
module.exports = function callBindBasic(args) {
	if (args.length < 1 || typeof args[0] !== 'function') {
		throw new $TypeError('a function is required');
	}

        if (typeof $actualApply !== 'function') throw new $TypeError(JSON.stringify($actualApply));

	return $actualApply(bind, $call, args);
};
```
and the output in the terminal is `{"default":false"}`

**Comment by ljharb** [comment] 2024-12-07 22:33
hmm - the `default` part is something i can fix, but it's still showing up as `false` which is strange. can you also `console.log(typeof Reflect?.apply)`?

**Comment by ljharb** [comment] 2024-12-07 22:34
actually, i wonder if this might be a misconfigured build tool, that's incorrectly treating `.js` files inside a different project as ESM.

**Comment by arcaderob** [comment] 2024-12-07 22:35
> actually, i wonder if this might be a misconfigured build tool, that's incorrectly treating `.js` files inside a different project as ESM. what node version are you using? if 22.12, can you try 22.11?

I'm actually on Node 18.18.0

**Comment by ljharb** [comment] 2024-12-07 22:36
Perhaps you've set up cypress or babel or similar to transpile things inside node_modules?

**Comment by arcaderob** [comment] 2024-12-07 22:44
> Perhaps you've set up cypress or babel or similar to transpile things inside node_modules?

I'm looking into this. But, this is something that just popped up yesterday. I understand that you have recently split this off from `call-bind` and that is why this package is new in the repo. I just don't know what would have changed between then and now

**Comment by ljharb** [comment] 2024-12-07 22:46
I also don't know, but previously it wasn't using `require` to get at a bound function for "apply", it was just computing it inline, so the issue might have been masked.

**Comment by arcaderob** [comment] 2024-12-07 23:26
So, it doesn't look like I am transpiling node_modules. So, that is good.
I will do a trace backwards through the packages and find out what is calling the method and why it is failing.

**Comment by arcaderob** [comment] 2024-12-09 04:14
I have traced my way through the code and the best that I can determine is that there is an issue here: https://github.com/ljharb/call-bind-apply-helpers/blob/main/reflectApply.js#L4

This line:
```module.exports = typeof Reflect === 'function' && Reflect.apply;```
Seems to be the issue. Reflect is an Object - https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Reflect

If I replace the line with ```module.exports = typeof Reflect === 'object' && Reflect.apply;``` or even jest ```module.exports = Reflect.apply;``` (which of course doesn't have the check), then everything works as expected.

I looked at your commit from the `call-bind` repo here: https://github.com/ljharb/call-bind/commit/81018fb78902ff5acbc6c09300780e97f0db6a34#diff-16e4f2d9a56d404fdb183325a6934eb66492d6ca41e6db70b68cd7c24dc7c315L3
and I see that you copied the code over, but I don't see how this ever worked.

Could you please provide any information that you may have on what could be the discrepancy here? Thanks!

**Comment by ljharb** [comment] 2024-12-09 05:16
aha, you’re right. that’s a bug in the code, but it should just result in it being false, which should still allow actualApply to work.

**Comment by arcaderob** [comment] 2024-12-09 05:35
> aha, you’re right. that’s a bug in the code, but it should just result in it being false, which should still allow actualApply to work.

It could be something on my end, but if reflectApply returns false, then this is what $reflectApply is set to in actualApply.js :
<img width="409" alt="Screenshot 2024-12-09 at 12 30 43 AM" src="https://github.com/user-attachments/assets/0aa5d0bf-3314-4f6c-ac8c-3a50c92e6a48">

so, `module.exports = $reflectApply || bind.call($call, $apply);` will return `{default: true}`

**Comment by ljharb** [comment] 2024-12-09 06:34
so, I certainly will fix `reflectApply`, but you'll still see `$reflectApply` as `{ default: Reflect.apply }` which means it will still be broken, because it should be seeing it as literally `Reflect.apply`.

**Comment by arcaderob** [comment] 2024-12-09 06:43
> so, I certainly will fix `reflectApply`, but you'll still see `$reflectApply` as `{ default: Reflect.apply }` which means it will still be broken, because it should be seeing it as literally `Reflect.apply`.

Weirdly, changing the check from `function` to `object` works on my end. Here is the logged outputs to the console of $reflectApply in actualApply.js

As `function`:
<img width="381" alt="Screenshot 2024-12-09 at 1 40 49 AM" src="https://github.com/user-attachments/assets/8fca9d49-cd75-4c57-bce7-41e8be5109c3">

As `object`:
<img width="281" alt="Screenshot 2024-12-09 at 1 40 03 AM" src="https://github.com/user-attachments/assets/24d7ef7a-df38-4b4c-b133-eb89cca1dede">

Thank you for your help with this!

**Comment by ljharb** [comment] 2024-12-09 06:48
Can you try changing it to `module.exports = x` where x is any primitive value? (perhaps, try all of the types of primitives?) i wonder if perhaps you've got something interfering when it's a primitive, that doesn't interfere when it's an object/function.

**Comment by arcaderob** [comment] 2024-12-09 06:56
> Can you try changing it to `module.exports = x` where x is any primitive value? (perhaps, try all of the types of primitives?) i wonder if perhaps you've got something interfering when it's a primitive, that doesn't interfere when it's an object/function.

Very odd! It seems to only do `{default: false}` when the returned value is `false`.
I tried `module.exports = 1;` and `module.exports = true;`. Both returned the hardcoded value.
Then, I tried `module.exports = false;` and it returned `{default: false}`.

I have no idea why this is, but, at the very least, your change appears to have fixed this issue.
Again, I appreciate your assistance on resolving this so quickly!

**Comment by ljharb** [comment] 2024-12-09 06:58
Very strange. The only possibilities I can think of are either 1) your setup is doing something weird, or 2) there's a bug in node, but one I can't reproduce.

I'll close this, but my strong suspicion is that it's something about your cypress setup.

**Closed by ljharb** 2024-12-09 06:58 UTC
